# Generated by Django 4.2.7 on 2026-05-31 00:27

import api.models.user
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("EDITOR", "Editor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="phone"),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="photo URL"
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "ui_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Shell preferences for the frontend (theme, page width, UI locale, appearance panel collapse state). Shallow-merged on PATCH; unknown keys are preserved.",
                        verbose_name="UI preferences",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["username"],
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", api.models.user.UserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Etiqueta para identificar la integración (ej. app móvil X).",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        editable=False,
                        help_text="Segmento público de la clave; forma parte del valor mostrado al crear.",
                        max_length=16,
                        unique=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "secret_hash",
                    models.CharField(
                        editable=False, max_length=128, verbose_name="secret hash"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Format: XXX-uuid4. Assigned on first save.",
                        max_length=40,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If enabled, becomes the only default menu; all other menus are cleared. Served to every authenticated user.",
                        verbose_name="default menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu",
                "verbose_name_plural": "menus",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "theme_key",
                    models.CharField(
                        choices=[
                            ("tmp-default", "Default (base)"),
                            ("tmp-light", "Light"),
                            ("tmp-dark", "Dark"),
                            ("tmp-blackandwhite", "High contrast (B/W)"),
                            ("tmp-beige", "Beige / warm"),
                        ],
                        default="tmp-default",
                        help_text="Tema que el front aplicará al arrancar (sobrescribe localStorage).",
                        max_length=32,
                        verbose_name="theme key",
                    ),
                ),
                (
                    "app_title",
                    models.CharField(
                        blank=True,
                        default="FVX Suscription",
                        help_text="Título mostrado en la pestaña del navegador (fase 2).",
                        max_length=100,
                        verbose_name="app title",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del logo de marca (fase 2).",
                        max_length=500,
                        null=True,
                        verbose_name="logo URL",
                    ),
                ),
                (
                    "theme_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override de variables CSS --fvx-* por clave (fase 2).",
                        verbose_name="theme overrides",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI settings",
                "verbose_name_plural": "UI settings",
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("apple", "Apple")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="Subject (sub) del id_token del proveedor.",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email visto al enlazar; Apple puede dejar de enviarlo en re-inicios.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "social account",
                "verbose_name_plural": "social accounts",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("operational", "Operational"),
                            ("critical", "Critical"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "link",
                    models.URLField(blank=True, max_length=500, verbose_name="link"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Format: XXX-uuid4. Assigned on first save.",
                        max_length=40,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="api.menu",
                        verbose_name="menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu section",
                "verbose_name_plural": "menu sections",
                "ordering": ["menu", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Format: XXX-uuid4. Assigned on first save.",
                        max_length=40,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "route",
                    models.CharField(
                        help_text="Path without domain, e.g. /users",
                        max_length=255,
                        verbose_name="route",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del glifo (ligature) de Google Material Icons (clásico), en snake_case; es el mismo texto que usa el frontend en Angular Material (`<mat-icon>nombre</mat-icon>`). El frontend carga Material Icons + Material Icons Outlined (NO Material Symbols), así que un glifo que solo exista en Symbols se vería en blanco. En el admin puedes usar las sugerencias al escribir (lista corta) o el enlace al catálogo. Catálogo: https://fonts.google.com/icons?icon.set=Material+Icons — Vacío: el frontend muestra el icono «label».",
                        max_length=80,
                        verbose_name="icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON list of role codes, e.g. ["VIEWER","ADMIN"]. Empty: only staff see this item (non-staff users will NOT); list roles to also grant matching non-staff users. Staff always see every item.',
                        verbose_name="allowed roles",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.menusection",
                        verbose_name="section",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
                "ordering": ["section", "order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["is_active"], name="api_menu_is_acti_2fabf7_idx"
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_keys_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario cuyos permisos tendrán las llamadas con esta clave.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(
                fields=["provider", "uid"], name="api_sociala_provide_558d28_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="api_socialaccount_user_provider_uniq"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialaccount",
            unique_together={("provider", "uid")},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read_at"], name="api_notific_user_id_85c543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created"], name="api_notific_user_id_3db720_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menusection",
            index=models.Index(
                fields=["menu", "is_active"], name="api_menusec_menu_id_fd4026_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["section", "is_active"], name="api_menuite_section_26f001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["user", "is_active"], name="api_apikey_user_id_90f679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="api_user_role_9b9076_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["verified"], name="api_user_verifie_e54b11_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_removed"], name="api_user_is_remo_f79a17_idx"
            ),
        ),
    ]
