# Generated by Django 4.2.7 on 2026-05-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("apple", "Apple"),
                    ("microsoft", "Microsoft"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
