# Generated by Django 4.2.7 on 2026-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_socialaccount_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Si se setea, la clave deja de autenticar después de esta fecha. Vacío = no expira.",
                null=True,
                verbose_name="expires at",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de scopes permitidos (ej. ["uploads.write"]). Vacío = sin restricción de scope (la clave hereda los permisos del usuario). Se exige con `require_api_key_scope` en las vistas que lo necesiten.',
                verbose_name="scopes",
            ),
        ),
    ]
