# Generated by Django 4.2.7 on 2026-06-14 23:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Format: XXX-uuid4. Assigned on first save.",
                        max_length=40,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "flow_plan_id",
                    models.CharField(
                        blank=True,
                        help_text="Stable identifier sent to Flow as planId (no spaces). Auto-derived from the slug on first save; do not change once synced.",
                        max_length=120,
                        unique=True,
                        verbose_name="Flow plan id",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Charge per period (CLP, whole pesos). Empty = draft / 'Valor por confirmar'.",
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CLP", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        choices=[
                            (1, "Daily"),
                            (2, "Weekly"),
                            (3, "Monthly"),
                            (4, "Yearly"),
                        ],
                        default=3,
                        help_text="Billing frequency.",
                        verbose_name="interval",
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Interval multiplier (e.g. interval=weekly + count=2 = fortnightly).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="interval count",
                    ),
                ),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="trial period (days)"
                    ),
                ),
                (
                    "days_until_due",
                    models.PositiveIntegerField(
                        default=3, verbose_name="days until due"
                    ),
                ),
                (
                    "periods_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total periods the plan lasts. Empty = open-ended.",
                        null=True,
                        verbose_name="number of periods",
                    ),
                ),
                (
                    "charges_retries_number",
                    models.PositiveIntegerField(
                        default=3, verbose_name="charge retries"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short subtitle, e.g. 'Sesión mensual · curso anual'.",
                        max_length=255,
                        verbose_name="tagline",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "cadence",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable cadence chip, e.g. 'Sesión mensual (curso anual)'.",
                        max_length=120,
                        verbose_name="cadence",
                    ),
                ),
                (
                    "recorded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether sessions are recorded (vs live-only).",
                        verbose_name="recorded",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of benefit strings shown with a check mark.",
                        verbose_name="features",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Material icon name, e.g. 'auto_awesome'.",
                        max_length=60,
                        verbose_name="icon",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight as 'Destacada'.",
                        verbose_name="featured",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show on the public memberships page.",
                        verbose_name="public",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "flow_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last synced to Flow"
                    ),
                ),
                (
                    "flow_status",
                    models.IntegerField(
                        blank=True,
                        help_text="Status returned by Flow: 1 active, 0 deleted.",
                        null=True,
                        verbose_name="Flow status",
                    ),
                ),
                (
                    "last_sync_error",
                    models.TextField(blank=True, verbose_name="last sync error"),
                ),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["order", "name"],
            },
        ),
    ]
