# Generated by Django 4.2.7 on 2026-06-15 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_seed_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "flow_customer_id",
                    models.CharField(max_length=120, verbose_name="Flow customer id"),
                ),
                (
                    "register_token",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Flow register token"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_card", "Pending card"),
                            ("subscribed", "Subscribed"),
                            ("failed", "Failed"),
                        ],
                        default="pending_card",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Flow subscription id"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="error")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_sessions",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "checkout session",
                "verbose_name_plural": "checkout sessions",
                "ordering": ["-created"],
            },
        ),
    ]
