# Generated by Django 4.2.7 on 2026-06-16 19:40

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_checkoutsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("newsletter", "Newsletter"),
                            ("contact", "Contact"),
                            ("maraton", "Maratón / event"),
                        ],
                        default="newsletter",
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Page/origin, e.g. 'home'.",
                        max_length=60,
                        verbose_name="source",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="country"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subject"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="raw payload"
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-created"],
            },
        ),
    ]
