# Generated by Django 4.2.7 on 2026-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Imagen opcional para la card (enriquecimiento local, no se envía a Flow).",
                max_length=500,
                verbose_name="image URL",
            ),
        ),
    ]
