# Generated by Django 4.2.7 on 2026-06-17 01:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_plan_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("pdf", "PDF / documento"),
                            ("text", "Texto"),
                            ("image", "Imagen"),
                            ("zoom", "Sesión Zoom (en vivo)"),
                            ("link", "Enlace"),
                        ],
                        default="video",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, verbose_name="text / description"),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="Archivo subido (video/audio/PDF/imagen).",
                        max_length=600,
                        verbose_name="file URL",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Link externo (YouTube/Vimeo/Zoom).",
                        max_length=600,
                        verbose_name="external URL",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado, no se muestra a los miembros.",
                        verbose_name="published",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "content item",
                "verbose_name_plural": "content items",
                "ordering": ["plan", "order", "-created"],
            },
        ),
    ]
