# Generated by Django 4.2.7 on 2026-06-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_contentitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentitem",
            options={
                "ordering": ["plan", "module", "order", "-created"],
                "verbose_name": "content item",
                "verbose_name_plural": "content items",
            },
        ),
        migrations.AddField(
            model_name="contentitem",
            name="module",
            field=models.CharField(
                blank=True,
                help_text="Agrupa items en módulos/lecciones (ej. 'Módulo 1'). Vacío = sin módulo.",
                max_length=160,
                verbose_name="module / section",
            ),
        ),
    ]
