# Generated by Django 4.2.7 on 2026-06-17 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_alter_contentitem_options_contentitem_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Format: XXX-uuid4. Assigned on first save.",
                        max_length=40,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subtitle"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha del evento. Vacío = próximamente.",
                        null=True,
                        verbose_name="date",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Precio de compra única en CLP. Vacío = 'Valor por confirmar' (no comprable).",
                        null=True,
                        verbose_name="price (CLP)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CLP", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Material icon, p. ej. 'wb_sunny'.",
                        max_length=60,
                        verbose_name="icon",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=600, verbose_name="image URL"
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="public")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["order", "date", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "commerce_order",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="commerce order"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="amount")),
                (
                    "flow_token",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Flow token"
                    ),
                ),
                (
                    "flow_order",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Flow order"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagada"),
                            ("failed", "Rechazada"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="subscriptions.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "event order",
                "verbose_name_plural": "event orders",
                "ordering": ["-created"],
            },
        ),
    ]
