# Generated by Django 4.2.7 on 2026-06-17 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0008_event_eventorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentitem",
            options={
                "ordering": ["order", "-created"],
                "verbose_name": "content item",
                "verbose_name_plural": "content items",
            },
        ),
        migrations.RemoveField(
            model_name="contentitem",
            name="module",
        ),
        migrations.RemoveField(
            model_name="contentitem",
            name="plan",
        ),
        migrations.AddField(
            model_name="contentitem",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Portada para la tarjeta de la biblioteca.",
                max_length=600,
                verbose_name="cover image URL",
            ),
        ),
        migrations.CreateModel(
            name="ContentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Desde cuándo el contenido está disponible en este plan.",
                        verbose_name="starts at",
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True,
                        help_text="Hasta cuándo. Vacío = sin fin.",
                        null=True,
                        verbose_name="ends at",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="subscriptions.contentitem",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_schedules",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "content schedule",
                "verbose_name_plural": "content schedules",
                "ordering": ["plan", "-starts_at"],
                "unique_together": {("content", "plan")},
            },
        ),
    ]
