# Generated by Django 4.2.7 on 2026-05-29 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BOUNCE_PERMANENT", "Rebote permanente"),
                            ("COMPLAINT", "Marcó como spam"),
                            ("UNSUBSCRIBE", "Se desuscribió"),
                            ("MANUAL", "Bloqueo manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Email suprimido",
                "verbose_name_plural": "Emails suprimidos",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("to_address", models.EmailField(db_index=True, max_length=254)),
                ("template_name", models.CharField(db_index=True, max_length=80)),
                ("subject", models.CharField(max_length=255)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(max_length=20)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENT", "Enviado al proveedor"),
                            ("DELIVERED", "Entregado al MTA destino"),
                            ("BOUNCED", "Rebotó"),
                            ("COMPLAINED", "Marcado como spam"),
                            ("FAILED", "Error al enviar"),
                            ("SUPPRESSED", "Destinatario en lista de supresión"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("bounce_type", models.CharField(blank=True, max_length=40)),
                ("bounce_subtype", models.CharField(blank=True, max_length=80)),
                ("complained_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "related_object_id",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["to_address", "-created"],
                        name="notificatio_to_addr_3a060d_idx",
                    ),
                    models.Index(
                        fields=["status", "-created"],
                        name="notificatio_status_ae49cf_idx",
                    ),
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="notificatio_related_47fbe7_idx",
                    ),
                ],
            },
        ),
    ]
